[workspace]
members = [
    "models",
    "server",
    "app",
]
resolver = "2"

[workspace.dependencies]
skyzen = { git = "file:///Users/lexoliu/Coding/skyzen", branch = "dev" }
zenwave = { version = "0.3", default-features = false, features = ["hyper-backend"] }
tracing = "0.1"
waterui = { path = "../waterui" }
waterui-ffi = { path = "../waterui/ffi" }
