[package]
name = "together-app"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
models = { path = "../models" }
waterui.workspace = true
waterui-ffi.workspace = true
waterui-icon = { path = "../../waterui/components/icon" }
zenwave.workspace = true
tracing.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
