dev_dependencies = true

[package]
name = "together"
display_name = "Together"
bundle_identifier = "com.waterui.together"
author = "Lexo Liu"

[backends.swift]
project_path = "apple"
scheme = "together"
project_file = "Together.xcodeproj"
branch = "dev"
revision = "c0c39a4a2a0c26a2e6835a4c8b695f50f8ae874c"
dev = true
ffi_version = "0.1.0"

[backends.android]
project_path = "android"
dev = true
ffi_version = "0.1.0"

[hot_reload]
watch = []
