[package]
name = "together-server"
version = "0.1.0"
edition = "2021"

[dependencies]
models = { path = "../models", features = ["openapi"] }
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
skyzen.workspace = true
async-std = "1.12.0"
sqlx = { version = "0.8", features = ["runtime-async-std-rustls", "macros", "sqlite", "postgres", "uuid", "chrono", "migrate"] }
serde = { version = "1.0.188" ,features = ["derive"]}
serde_json = "1.0"
bytes = "1.5.0"
ring = "0.16.20"
rand = "0.8.5"
csv = "1.4.0"
time = { version = "0.3.28", features = ["formatting"] }
hex = "0.4.3"
bytestr = { version = "0.1.0", features = ["serde"] }
log = "0.4.20"
futures-util = "0.3.28"
uuid = { version = "1.4", features = ["serde", "v4"] }
utoipa = "5.4.0"
linkme = "0.3.35"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[features]
openapi = []

[dev-dependencies]
skyzen-test = { path = "../../skyzen/test" }
