#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

LANGUAGE_BY_SUFFIX = {
    ".rs": "rust",
    ".swift": "swift",
    ".ts": "typescript",
    ".tsx": "tsx",
    ".css": "css",
    ".toml": "toml",
    ".sh": "bash",
    ".js": "javascript",
    ".json": "json",
}

GLOBAL_EXCLUDED_DIR_NAMES = {
    ".claude",
    ".git",
    "dist",
    "node_modules",
    "target",
    "xcuserdata",
}

GLOBAL_EXCLUDED_PREFIXES = (
    PurePosixPath("app"),
    PurePosixPath("official_doc_sample"),
)

GLOBAL_EXCLUDED_FILES = {
    PurePosixPath("Cargo.lock"),
    PurePosixPath("admin/bun.lock"),
}

GLOBAL_EXCLUDED_SUFFIXES = {
    ".db",
    ".pdf",
    ".png",
    ".xcuserstate",
}


@dataclass(frozen=True)
class SectionSpec:
    title: str
    roots: tuple[str, ...] = ()
    explicit_files: tuple[str, ...] = ()
    allowed_suffixes: tuple[str, ...] = ()
    excluded_prefixes: tuple[str, ...] = ()


SECTIONS = (
    SectionSpec(
        title="SHARED MODELS",
        roots=("models/src",),
        explicit_files=("models/Cargo.toml",),
        allowed_suffixes=(".rs", ".toml"),
    ),
    SectionSpec(
        title="SERVER",
        roots=("server/src",),
        explicit_files=("server/Cargo.toml",),
        allowed_suffixes=(".rs", ".toml"),
    ),
    SectionSpec(
        title="ADMIN PANEL",
        roots=("admin/src",),
        explicit_files=(
            "admin/package.json",
            "admin/tsconfig.json",
            "admin/vite.config.ts",
            "admin/eslint.config.js",
        ),
        allowed_suffixes=(".ts", ".tsx", ".css", ".js", ".json"),
        excluded_prefixes=("admin/src/assets", "admin/src/components/ui"),
    ),
    SectionSpec(
        title="STUDENT IPAD APP",
        roots=("swiftui/together",),
        allowed_suffixes=(".swift",),
    ),
    SectionSpec(
        title="STUDENT IPAD APP TESTS",
        roots=("swiftui/togetherTests", "swiftui/togetherUITests"),
        allowed_suffixes=(".swift",),
    ),
    SectionSpec(
        title="WORKSPACE & SCRIPTS",
        explicit_files=("Cargo.toml", "scripts/init-demo.sh"),
        allowed_suffixes=(".toml", ".sh"),
    ),
)


TYPST_TEMPLATE_LINES = (
    "// Generated by scripts/generate-source-appendix.py. Do not edit.",
    "#set document(title: \"Appendix 3: Source Code\")",
    "#set page(paper: \"a4\", margin: (x: 1.7cm, y: 1.9cm))",
    "#set text(font: \"New Computer Modern\", size: 10pt)",
    "#set par(leading: 0.58em, justify: true)",
    "#set heading(numbering: none)",
    "#set raw(block: true, theme: auto)",
    "",
    "#let navy = rgb(\"#183153\")",
    "#let sky = rgb(\"#4d7ac7\")",
    "#let manifest = json(\"__MANIFEST_PATH__\")",
    "",
    "#show heading.where(level: 1): it => {",
    "  pagebreak(weak: true)",
    "  v(38%)",
    "  align(center)[",
    "    #text(size: 28pt, weight: \"bold\")[#it.body]",
    "  ]",
    "  pagebreak()",
    "}",
    "",
    "#show heading.where(level: 2): it => {",
    "  v(0.7em)",
    "  text(size: 14pt, style: \"italic\", fill: sky, it.body)",
    "  v(0.2em)",
    "  line(length: 100%, stroke: 0.5pt + luma(175))",
    "  v(0.45em)",
    "}",
    "",
    "#show outline.entry: it => {",
    "  set text(weight: if it.level == 1 { \"bold\" } else { \"regular\" })",
    "  it",
    "}",
    "",
    "#show raw.where(block: true): it => block(",
    "  width: 100%,",
    "  inset: 10pt,",
    "  fill: rgb(\"#fcfcfd\"),",
    "  stroke: 0.5pt + luma(220),",
    "  radius: 3pt,",
    ")[#it]",
    "",
    "#let render-file(file) = {",
    "  heading(level: 2)[#file.path]",
    "  raw(read(file.path), block: true, lang: file.lang)",
    "}",
    "",
    "#align(center)[",
    "  #text(size: 20pt, weight: \"bold\", fill: navy)[APPENDIX 3: SOURCE CODE]",
    "]",
    "",
    "#v(1.2em)",
    "",
    "#align(center)[",
    "  #text(size: 18pt, weight: \"bold\")[Contents]",
    "]",
    "",
    "#v(1em)",
    "",
    "#outline(title: none, depth: 2)",
    "",
    "#for section in manifest.sections {",
    "  heading(level: 1)[#section.title]",
    "  for file in section.files {",
    "    render-file(file)",
    "  }",
    "}",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the Typst sources for the source code appendix.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repository root.",
    )
    parser.add_argument(
        "--manifest-output",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "appendix" / "source-code-manifest.json",
        help="Manifest output path.",
    )
    parser.add_argument(
        "--typst-output",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "Appendix_3_Source_Code.typ",
        help="Generated Typst output path.",
    )
    return parser.parse_args()


def to_rel_path(root: Path, path: Path) -> PurePosixPath:
    return PurePosixPath(path.relative_to(root).as_posix())


def has_prefix(path: PurePosixPath, prefix: PurePosixPath) -> bool:
    return path.parts[: len(prefix.parts)] == prefix.parts


def is_globally_excluded(rel_path: PurePosixPath) -> bool:
    if any(part in GLOBAL_EXCLUDED_DIR_NAMES for part in rel_path.parts[:-1]):
        return True
    if any(has_prefix(rel_path, prefix) for prefix in GLOBAL_EXCLUDED_PREFIXES):
        return True
    if rel_path in GLOBAL_EXCLUDED_FILES:
        return True
    if rel_path.suffix in GLOBAL_EXCLUDED_SUFFIXES:
        return True
    return False


def is_section_excluded(rel_path: PurePosixPath, spec: SectionSpec) -> bool:
    return any(has_prefix(rel_path, PurePosixPath(prefix)) for prefix in spec.excluded_prefixes)


def language_for(path: PurePosixPath) -> str:
    language = LANGUAGE_BY_SUFFIX.get(path.suffix)
    if language is None:
        raise ValueError(f"No Typst raw language mapping for {path}")
    return language


def add_explicit_file(root: Path, rel_file: str, spec: SectionSpec, selected: dict[str, dict[str, str]]) -> None:
    abs_path = root / rel_file
    if not abs_path.is_file():
        raise FileNotFoundError(f"Expected appendix source file does not exist: {rel_file}")

    rel_path = to_rel_path(root, abs_path)
    if is_globally_excluded(rel_path) or is_section_excluded(rel_path, spec):
        raise ValueError(f"Explicit appendix source file is excluded by policy: {rel_path}")
    if rel_path.suffix not in spec.allowed_suffixes:
        raise ValueError(f"Explicit appendix source file has unsupported suffix: {rel_path}")

    selected[rel_path.as_posix()] = {
        "path": rel_path.as_posix(),
        "lang": language_for(rel_path),
    }


def add_scanned_files(root: Path, rel_root: str, spec: SectionSpec, selected: dict[str, dict[str, str]]) -> None:
    abs_root = root / rel_root
    if not abs_root.is_dir():
        raise FileNotFoundError(f"Expected appendix source directory does not exist: {rel_root}")

    for abs_path in abs_root.rglob("*"):
        if not abs_path.is_file():
            continue

        rel_path = to_rel_path(root, abs_path)
        if is_globally_excluded(rel_path) or is_section_excluded(rel_path, spec):
            continue
        if rel_path.suffix not in spec.allowed_suffixes:
            continue

        selected[rel_path.as_posix()] = {
            "path": rel_path.as_posix(),
            "lang": language_for(rel_path),
        }


def build_section(root: Path, spec: SectionSpec) -> dict[str, object]:
    selected: dict[str, dict[str, str]] = {}

    for rel_file in spec.explicit_files:
        add_explicit_file(root, rel_file, spec, selected)

    for rel_root in spec.roots:
        add_scanned_files(root, rel_root, spec, selected)

    files = [selected[path] for path in sorted(selected)]
    if not files:
        raise ValueError(f"Appendix section is empty: {spec.title}")

    return {
        "title": spec.title,
        "files": files,
    }


def build_manifest(root: Path) -> dict[str, object]:
    return {
        "sections": [build_section(root, spec) for spec in SECTIONS],
    }


def typst_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def build_typst(manifest_output: Path, typst_output: Path) -> str:
    rel_manifest_path = Path(os.path.relpath(manifest_output, typst_output.parent)).as_posix()
    escaped_manifest_path = typst_string(rel_manifest_path)
    return "\n".join(
        line.replace("__MANIFEST_PATH__", escaped_manifest_path)
        for line in TYPST_TEMPLATE_LINES
    ) + "\n"


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    manifest_output = args.manifest_output.resolve()
    typst_output = args.typst_output.resolve()

    if not root.is_dir():
        raise FileNotFoundError(f"Repository root does not exist: {root}")

    manifest_output.parent.mkdir(parents=True, exist_ok=True)
    typst_output.parent.mkdir(parents=True, exist_ok=True)

    manifest = build_manifest(root)
    manifest_output.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    typst_output.write_text(build_typst(manifest_output, typst_output), encoding="utf-8")

    section_count = len(manifest["sections"])
    file_count = sum(len(section["files"]) for section in manifest["sections"])
    print(
        f"Wrote {file_count} appendix files across {section_count} sections "
        f"to {manifest_output} and {typst_output}"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:  # noqa: BLE001
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1)
